Repository avinashkranjan/Friday, pull requests merged in 2021-03, with the labels that each got.

#62 For #55 Replaced deprecated widgets and updates plugins according to Flutter v2
  lib/screens/home_screen.dart
  lib/screens/onboarding_page.dart
  lib/screens/welcome_screen.dart
  lib/widgets/login_form.dart
  lib/widgets/recents_homeworks.dart
  lib/widgets/signup_form_additional_details.dart
  lib/widgets/signup_form_essential_details.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level 2

#54 Form Detail Correction
  lib/screens/profile_screen.dart
  lib/widgets/signup_form_additional_details.dart
  pubspec.lock
Labels: Approved, GSSOC21, Level0

#69 Added feature to toggle obscurity
  lib/widgets/auth_input_form_field.dart
  lib/widgets/login_form.dart
  lib/widgets/signup_form_essential_details.dart
Labels: Approved, GSSOC21, Level2

#70 Google Authentication With Authenticate Data Store in FireStore Added
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/values-night/styles.xml
  assets/images/google.png
  lib/screens/onboarding_page.dart
  lib/screens/profile_screen.dart
  lib/services/googleAuthentication.dart
  lib/widgets/signup_form_additional_details.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved, GSSOC21, Level3

#85 Facebook Authentication Added With Exception Handling( #71 )
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  assets/images/fbook.png
  lib/screens/onboarding_page.dart
  lib/screens/profile_screen.dart
  lib/services/facebookAuthentication.dart
  lib/services/googleAuthentication.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved, GSSOC21, Level3

#82 Refactored onboarding_page.dart
  lib/screens/onboarding_page.dart
  lib/widgets/round_button.dart
Labels: Approved, GSSOC21, Level1

#79 forgot password feature
  lib/widgets/login_form.dart
  lib/widgets/reset_password.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved, GSSOC21, Level3

#86 Increased the margin for logout button to make it visible
  lib/screens/profile_screen.dart
Labels: Approved, GSSOC21, Level0

#92 Sign-up Log-in Email Verification Added(#81)
  lib/screens/profile_screen.dart
  lib/services/authentication.dart
  lib/services/user_db_services.dart
  lib/widgets/login_form.dart
  lib/widgets/signup_form_additional_details.dart
  pubspec.lock
Labels: Approved, GSSOC21, Level3

#96 Keyboard Restriction Added for College Academic Year
  lib/widgets/auth_input_form_field.dart
  lib/widgets/signup_form_additional_details.dart
Labels: Approved, GSSOC21, Level0

#107 Update README.md
  README.md
Labels: GSSOC21, Level0

#105 Now Without log-in user can't navigate to bottom navigation page
  lib/screens/login_page.dart
Labels: Approved, GSSOC21, Level1, bug

#99 Replacing classes data from hard-coded to firestore
  .gitignore
  lib/models/classes.dart
  lib/models/users.dart
  lib/widgets/build_classes.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved, GSSOC21, Level3

#97 Changed college textfield to dropdown with dropdown values from firebase
  lib/constants.dart
  lib/widgets/signup_form_additional_details.dart
Labels: Approved, GSSOC21, Level2

#114 Search Bar focused border added.
  lib/screens/home_screen.dart
Labels: Approved, GSSOC21, Level2

#117 Wiki Pages Added as README File
  WikiPagesREADME.md
Labels: Approved, GSSOC21, Level1

#116 HEADING
  lib/screens/loading_screen.dart
  lib/widgets/header.dart
Labels: Approved, GSSOC21, Level2

#108 Added image picker
  android/app/src/main/AndroidManifest.xml
  android/settings_aar.gradle
  ios/Runner/Info.plist
  lib/screens/profile_screen.dart
  lib/services/user_db_services.dart
  lib/services/user_info_services.dart
  lib/widgets/header.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved, GSSOC21, Level3

#119 Issue 103
  lib/models/classes.dart
  lib/services/classes_db_services.dart
  lib/widgets/build_classes.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved, GSSOC21, Level3

#122 Now user data gets fetched on first login
  lib/screens/profile_screen.dart
  lib/services/authentication.dart
  lib/widgets/header.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved, GSSOC21, Level2

#125 Dropdown for Courses, Stream Added with add data to firebase
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  lib/screens/profile_screen.dart
  lib/services/classes_db_services.dart
  lib/widgets/signup_form_additional_details.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved, GSSOC21, Level3

#127 Proper Age Validation Added in Sign-up form additional Details
  lib/widgets/signup_form_additional_details.dart
Labels: GSSOC21, Level2

#123 Added auto label for issues
  .github/workflows/issue.yml
Labels: GSSOC21, Level0
