Repository avinashkranjan/Friday, pull requests merged in 2021-04, with the labels that each got.

#135 [Fixes] : Landing page content override
  lib/screens/onboarding_page.dart
Labels: Approved, GSSOC21, Level2

#133 Now After Google/FB Sign-in user navigate to `additional details` page and then `bottom navigation` page instead of `log-in` page
  lib/screens/signup_additional_details_screen.dart
  lib/services/facebookAuthentication.dart
  lib/services/googleAuthentication.dart
  lib/widgets/signup_form_additional_details.dart
Labels: Approved, GSSOC21, Level2

#143 Now Firestore can't affect by Scammers
  lib/screens/signup_additional_details_screen.dart
  lib/services/authentication.dart
  lib/services/facebookAuthentication.dart
  lib/services/googleAuthentication.dart
  lib/services/user_db_services.dart
  lib/widgets/signup_form_additional_details.dart
Labels: Approved, GSSOC21, Level2

#144 FIX: HW page error Issue #139
  lib/screens/homework_screen.dart
Labels: Approved, GSSOC21, Level0

#140 [Fixes] : wrong bottom navigation on login
  lib/screens/profile_screen.dart
  lib/utils/bottom_navbar_tabs.dart
Labels: Approved, GSSOC21, Level2, bug

#138 FIX: AlertsPageError Issue #132
  lib/screens/alert_screen.dart
Labels: Approved, GSSOC21, Level1

#151 Add Design Wireframe for Website
  Design Wireframe/Design Wireframe.png
Labels: GSSOC21, Level1, enhancement

#153 classes UI : table calendar format
  lib/models/users.dart
  lib/screens/classes_screen.dart
  lib/services/classes_db_services.dart
  lib/widgets/build_classes.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level3, enhancement

#149 Add New Class Manually by user with Separate Day
  lib/models/classes.dart
  lib/models/users.dart
  lib/screens/classes_screen.dart
  lib/services/classes_db_services.dart
  lib/widgets/build_classes.dart
  lib/widgets/header.dart
  lib/widgets/signup_form_additional_details.dart
  pubspec.yaml
Labels: Approved, GSSOC21, Level3, enhancement

#156 fixed overflow at signup page
  lib/widgets/signup_form_additional_details.dart
Labels: Approved, GSSOC21, Level2, bug-fix

#159 Added no.of forks,issues,pr's and license,repo size
  README.md
Labels: Approved, GSSOC21, Level0, enhancement, good first issue

#154 Readme enhanced
  README.md
Labels: GSSOC21, Level0, enhancement

#161 Added Design Prototype for Website
  Design Prototype/Design-Prototype-Dark Theme.png
  Design Prototype/Design-Prototype-Light Theme.png
Labels: GSSOC21, Level2, enhancement

#152 FEAT: HomePage Search Error Issue #136
  lib/screens/home_screen.dart
Labels: GSSOC21, Level2, bug-fix
