Repository avinashkranjan/Friday, pull requests merged in 2021-05, with the labels that each got.

#130 Added Editable_Profile
  lib/screens/profile_screen.dart
  lib/services/user_db_services.dart
Labels: Approved, GSSOC21, Level2

#166 Updated Bug Report Template (#165)
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Approved, GSSOC21, Level0

#163 Update README.md
  README.md
Labels: GSSOC21, Level0
