Repository avinashkranjan/Friday, pull requests merged in 2023-06, with the labels that each got.

#227 modified: facebookAuthentication.dart file
  lib/services/facebookAuthentication.dart
Labels: level1, gssoc23

#233 modified: home_screen.dart file
  lib/screens/home_screen.dart
Labels: level1, gssoc23

#240 Version Updated
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/gradle/wrapper/gradle-wrapper.properties
Labels: level1, gssoc23

#242 widgets/round_button.dart file fixed
  lib/widgets/round_button.dart
Labels: level1, gssoc23

#230 added color scheme
  Color scheme/color_design.md
Labels: level2, gssoc23

#247 Code Issues Resolved
  lib/widgets/build_classes.dart
Labels: level2, gssoc23

#249 bottom_navigation.dart Errors resolved
  lib/widgets/bottom_navigation.dart
Labels: level1, gssoc23

#251 modified homework.dart file
  lib/models/homework.dart
Labels: level1, gssoc23

#253 Modified: animated_nav_bar.dart file
  lib/widgets/animated_nav_bar.dart
Labels: level1, gssoc23

#255 Enhancing profile_screen
  lib/screens/profile_screen.dart
Labels: level2, gssoc23

#257 Modified: googleAuthentication.dart
  lib/services/googleAuthentication.dart
Labels: level1, gssoc23

#259 modified: classes_screen.dart
  lib/screens/classes_screen.dart
Labels: level1, gssoc23

#261 Modified: auth_handling_widget.dart
  lib/widgets/auth_handling_widget.dart
Labels: level1, gssoc23

#262 Update README.md
  README.md
Labels: level1, gssoc23

#265 Modified: classes_db_services.dart
  lib/services/classes_db_services.dart
Labels: level2, gssoc23

#267 recents_homeworks.dart file fixed
  lib/widgets/recents_homeworks.dart
Labels: level1, gssoc23

#269 reset_password.dart file fixed
  lib/widgets/reset_password.dart
Labels: level1, gssoc23

#271 Improvements in README.md #270
  README.md
Labels: level1, gssoc23

#275 Updates
  pubspec.lock
  pubspec.yaml
Labels: level1, gssoc23

#277 authentication.dart file fixed
  lib/services/authentication.dart
Labels: level1, gssoc23

#281 loading_screen.dart file fixed
  lib/screens/loading_screen.dart
Labels: level1, gssoc23

#283 Modified: user_info_services.dart
  lib/services/user_info_services.dart
Labels: level1, gssoc23

#287 Updated bottom_navigation.dart file
  lib/widgets/bottom_navigation.dart
Labels: level1, gssoc23

#290 Code Issues Resolved
  android/app/build.gradle
  lib/main.dart
  lib/models/users.dart
  lib/screens/profile_screen.dart
  lib/services/user_db_services.dart
  lib/services/user_info_services.dart
  lib/widgets/header.dart
Labels: level2, gssoc23

#293 doc:Created Issue button and forms respectively
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: level2, gssoc23

#294 Created I GitHub Workflow that Comment on Action Like PR, Issue Open And Close
  .github/workflows/auto-comment.yml
  .github/workflows/greetings.yml
Labels: level2, gssoc23

#296 Website for "Friday App"
  friday_home_image.webp
  friday_website_logo.webp
  index.html
  main.js
  screenshot_1.webp
  screenshot_2.webp
  screenshot_3.webp
  style.css
Labels: level2, gssoc23

#297 Issue#285
  lib/widgets/signup_form_additional_details.dart
Labels: level2, gssoc23

#299 Removing Deprecated Splash Screen Implementation
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
Labels: level1, gssoc23

#301 Loading screen error fixed
  lib/screens/loading_screen.dart
Labels: level1, gssoc23

#304 added Onboarding and Intro Slider for new users
  assets/images/slider1.png
  assets/images/slider2.png
  assets/images/slider3.png
  lib/main.dart
  lib/onboarding/introslider.dart
  lib/screens/onboarding_page.dart
  lib/screens/splash.dart
  lib/screens/welcome_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: level3, gssoc23

#308 Code issues resolved
  pubspec.lock
  pubspec.yaml
Labels: level1, gssoc23
