Repository avinashkranjan/Friday, pull requests merged in 2023-05, with the labels that each got.

#185 For Update all dependencies and version of This Flutter project (Friday)
  android/build.gradle
  pubspec.lock
  pubspec.yaml
Labels: Level1, gssoc23

#197 Update README.md
  README.md
Labels: level1, gssoc23

#199 modified: CircleAvatar Widget
  lib/widgets/header.dart
Labels: level1, gssoc23

#193 Updating the the logo of the project
  README.md
Labels: level1, gssoc23

#206 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, gssoc23

#208 added light mode designs
  Design Prototype/regis (1).png
  Design Prototype/regis.png
  Design Prototype/slash.png
Labels: level2, gssoc23

#212 Code Issues Resolved and Corrected
  lib/models/users.dart
Labels: level2, gssoc23

#217 modified: countdown_painter file
  lib/widgets/countdown_painter.dart
Labels: level2, gssoc23

#220 modified: auth_input_form_field.dart file
  lib/widgets/auth_input_form_field.dart
Labels: level1, gssoc23

#222 modified: signup_form_essential_details.dart
  lib/widgets/signup_form_essential_details.dart
Labels: level2, gssoc23
