Repository avinashkranjan/Friday, pull requests merged in 2023-07, with the labels that each got.

#311 Feature - Added: Created Workflow for Code Formatting ⚡
  .github/workflows/lint.yml
Labels: level2, gssoc23

#313 Rating and feedback feature added
  lib/feedback.dart
  lib/main.dart
Labels: level2, gssoc23

#315 Bio feature added
  lib/models/users.dart
  lib/screens/profile_screen.dart
  lib/services/user_db_services.dart
Labels: level2, gssoc23

#324 animated_nav_bar.dart file fixed
  lib/widgets/animated_nav_bar.dart
Labels: level1, gssoc23

#326 Docker file is added
  Dockerfile
  android/.settings/org.eclipse.buildship.core.prefs
  android/gradle/wrapper/gradle-wrapper.properties
Labels: level3, gssoc23

#327 added "Favourites" section and fixed the issue 319
  lib/main.dart
  lib/onboarding/introslider.dart
  lib/screens/favourites_screen.dart
  lib/screens/home_screen.dart
  lib/widgets/recents_alerts.dart
  lib/widgets/signup_form_additional_details.dart
  pubspec.lock
  pubspec.yaml
Labels: level2, level3, gssoc23

#331 dependencies added
  pubspec.lock
  pubspec.yaml
Labels: level1, gssoc23

#333 README.md File improved
  README.md
Labels: level1, gssoc23

#338 Chat Feature added
  lib/screens/chat_screen.dart
  lib/screens/home_screen.dart
  lib/screens/new_group_screen.dart
  lib/services/chats_db.dart
Labels: level3, gssoc23

#341 Adding Phone Verification Feature to Sign Up Process
  assets/images/phone.png
  lib/main.dart
  lib/screens/onboarding_page.dart
  lib/screens/phone_verification_screen.dart
  lib/screens/verify_code_screen.dart
  lib/services/phone_number_verification_db.dart
Labels: level3, gssoc23

#343 Auto assign feature
  .github/workflows/issue-assign.yml
Labels: level2, gssoc23

#345 FAQ Feature added
  lib/main.dart
  lib/screens/faqs_screen.dart
  lib/screens/settings_screen.dart
Labels: level2, gssoc23

#347 Theme feature added
  lib/main.dart
  lib/screens/settings_screen.dart
  lib/screens/theme_screen.dart
  lib/screens/themes.dart
Labels: level2, gssoc23

#337 Dynamic GSSOC banner
  README.md
Labels: level1, gssoc23

#329 Progress Graph added
  lib/screens/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: level3, gssoc23

#353 Codeql Workflow Added
  .github/workflows/codeql.yml
Labels: level2, gssoc23

#351 Added share app functionality(issue #336) and created settings section(issue #340)
  android/app/src/main/AndroidManifest.xml
  assets/icons/settings.svg
  lib/main.dart
  lib/screens/home_screen.dart
  lib/screens/profile_screen.dart
  lib/screens/settings_screen.dart
  lib/utils/bottom_navbar_tabs.dart
  lib/widgets/bottom_navigation.dart
  pubspec.lock
  pubspec.yaml
Labels: level2, level3, gssoc23

#359 Dependencies Added
  pubspec.lock
  pubspec.yaml
Labels: level1, gssoc23

#363 feat: ⚙️ GitHub repo configs added
  .github/workflows/release.yml
Labels: level3, gssoc23

#362 changed UI of help and FAQ sections
  lib/screens/contact_us_screen.dart
  lib/screens/faqs_screen.dart
  lib/screens/help_screen.dart
Labels: level3, gssoc23

#366 Added Notifications and Light/Dark mode options in settings
  lib/screens/home_screen.dart
  lib/screens/settings_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: level2, level3, gssoc23

#367 Adding API for sending user queries through contact us page
  lib/screens/contact_us_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: level3, gssoc23

#374 Changed UI of App Ingo screen and resolved bugs
  lib/screens/app_info_screen.dart
  lib/widgets/build_classes.dart
Labels: level2, level3, gssoc23

#382 Resolved non-visible UI components in Calender table in BuildClasses screen
  lib/widgets/build_classes.dart
Labels: level3, gssoc23
