Repository avinashkranjan/Friday, pull requests merged in 2023-08, with the labels that each got.

#384 added mark all as unfavourite option
  lib/screens/favourites_screen.dart
  lib/screens/home_screen.dart
  lib/widgets/recents_alerts.dart
  pubspec.lock
Labels: level2, gssoc23

#385 Added support for hindi language
  lib/l10n/app_en.arb
  lib/l10n/app_hi.arb
  lib/main.dart
  lib/screens/alert_screen.dart
  lib/screens/favourites_screen.dart
  lib/screens/home_screen.dart
  lib/screens/homework_screen.dart
  lib/screens/profile_screen.dart
  lib/screens/settings_screen.dart
  lib/services/classes_db_services.dart
  lib/utils/notifications.dart
  lib/widgets/build_classes.dart
  lib/widgets/header.dart
  lib/widgets/recents_alerts.dart
  pubspec.lock
  pubspec.yaml
Labels: level3, gssoc23

#388 Implemented the local notifications in the application
  lib/main.dart
  lib/utils/notifications.dart
Labels: level3, gssoc23

#392 Added classes on button click to firestore database
  lib/services/classes_db_services.dart
  lib/widgets/recents_alerts.dart
Labels: level3, gssoc23

#390 Added flutter localizations support for multiple languages
  lib/l10n/app_en.arb
  lib/l10n/app_ru.arb
  lib/localizationTexts/hindi.dart
  lib/localizationTexts/russian.dart
  pubspec.lock
Labels: level3, gssoc23

#403 Added Change Language option in Settings
  lib/main.dart
  lib/screens/home_screen.dart
  lib/screens/settings_screen.dart
  lib/widgets/build_classes.dart
  lib/widgets/recents_alerts.dart
Labels: level3, gssoc23

#410 Added Gujarati Language support for the project
  lib/l10n/app_gu.arb
  lib/localizationTexts/gujarati.dart
  lib/main.dart
Labels: level2, gssoc23

#412 Resolved: Support development option now functioning.
  lib/main.dart
  lib/screens/settings_screen.dart
Labels: level2, gssoc23

#411 Modified UI of search bar in home screen
  lib/main.dart
  lib/screens/home_screen.dart
  lib/widgets/build_classes.dart
Labels: level2, gssoc23

#364 feat: init commit lint✔
  .gitignore
  .husky/commit-msg
  android/.settings/org.eclipse.buildship.core.prefs
  commitlint.config.js
  package-lock.json
  package.json
Labels: level3, gssoc23

#418 fix: Updated titles according to the latest docs
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: documentation, level1, gssoc23

#414 fix: Added gssoc & admin social handles links
  README.md
Labels: level1, gssoc23

#426 Update profile_screen.dart
  lib/screens/profile_screen.dart
Labels: level2, gssoc23

#425 Updated the color schema and UI of light mode
  lib/screens/themes.dart
Labels: level2, gssoc23

#422 Added Light theme in app
  lib/main.dart
  lib/screens/settings_screen.dart
  lib/screens/themes.dart
  lib/services/theme_provider.dart
Labels: level2, gssoc23
